김결정 has connected to Discord!
  File "./decision_kim.py", line 46
    keyword = message.content.split()[1]+\'n'
                                            ^
SyntaxError: unexpected character after line continuation character
김결정 has connected to Discord!
  File "./decision_kim.py", line 52
    if keyword[0] = ' ':
                  ^
SyntaxError: invalid syntax
김결정 has connected to Discord!
김결정 has connected to Discord!
김결정 has connected to Discord!
김결정 has connected to Discord!
김결정 has connected to Discord!
김결정 has connected to Discord!
김결정 has connected to Discord!
Ignoring exception in on_member_join
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 37, in on_member_join
    f'안뇽! 어서와ㅏㅏ {member.name}!'
  File "/usr/local/lib/python3.6/dist-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/usr/local/lib/python3.6/dist-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 114, in on_message
    world_boss = normal_boss * seed - (0.1 * seed)
UnboundLocalError: local variable 'normal_boss' referenced before assignment
Ignoring exception in on_member_join
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 37, in on_member_join
    f'안뇽! 어서와ㅏㅏ {member.name}!'
  File "/usr/local/lib/python3.6/dist-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/usr/local/lib/python3.6/dist-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_member_join
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./decision_kim.py", line 37, in on_member_join
    f'안뇽! 어서와ㅏㅏ {member.name}!'
  File "/usr/local/lib/python3.6/dist-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/usr/local/lib/python3.6/dist-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
김결정 has connected to Discord!
4 1
1
[1]
4 4
4
[]
6 4
4
[4]
6 4
3
3
[4, 3]
6 6
6
[]
1 6
6
[6]
1 4
4
[6, 4]
1 3
3
[6, 4, 3]
1 4
2
2
[6, 4, 3, 2]
1 3
4
2
6
2
4
6
2
2
4
6
6
3
2
2
2
6
4
4
5
5
[6, 4, 3, 2, 5]
1 3
4
4
1
1
[]
5 2
2
[2]
5 1
1
[2, 1]
5 1
1
1
2
6
6
[2, 1, 6]
5 3
3
[2, 1, 6, 3]
5 4
4
[2, 1, 6, 3, 4]
5 4
6
1
5
5
[]
3 4
4
[4]
3 4
1
1
[4, 1]
3 5
5
[4, 1, 5]
3 1
1
5
5
1
2
2
[4, 1, 5, 2]
3 4
5
6
6
[4, 1, 5, 2, 6]
3 1
1
6
1
2
2
1
4
2
3
3
[]
5 2
2
[2]
5 5
5
[]
5 5
5
[]
4 1
1
[1]
4 1
6
6
[1, 6]
4 5
5
[1, 6, 5]
4 3
3
[1, 6, 5, 3]
4 1
2
2
[1, 6, 5, 3, 2]
4 1
4
4
[]
5 2
2
[2]
5 5
5
[]
4 2
2
[2]
4 1
1
[2, 1]
4 1
4
4
[]
4 1
1
[1]
4 1
5
5
[1, 5]
4 4
4
[]
3 2
2
[2]
3 1
1
[2, 1]
3 5
5
[2, 1, 5]
3 2
4
4
[2, 1, 5, 4]
3 1
3
3
[]
1 1
1
[]
5 2
2
[2]
5 2
1
1
[2, 1]
5 1
6
6
[2, 1, 6]
5 3
3
[2, 1, 6, 3]
5 4
4
[2, 1, 6, 3, 4]
5 3
5
5
[]
5 2
2
[2]
5 3
3
[2, 3]
5 5
5
[]
3 3
3
[]
5 4
4
[4]
5 3
3
[4, 3]
5 2
2
[4, 3, 2]
5 3
1
1
[4, 3, 2, 1]
5 6
6
[4, 3, 2, 1, 6]
5 5
5
[]
1 6
6
[6]
1 2
2
[6, 2]
1 2
4
4
[6, 2, 4]
1 2
1
1
[]
5 4
4
[4]
5 3
3
[4, 3]
5 1
1
[4, 3, 1]
5 6
6
[4, 3, 1, 6]
5 2
2
[4, 3, 1, 6, 2]
5 5
5
[]
2 4
4
[4]
2 3
3
[4, 3]
2 2
2
[]
2 4
4
[4]
2 6
6
[4, 6]
2 5
5
[4, 6, 5]
2 6
3
3
[4, 6, 5, 3]
2 5
6
3
6
6
3
3
2
2
[]
3 5
5
[5]
3 2
2
[5, 2]
3 2
1
1
[5, 2, 1]
3 4
4
[5, 2, 1, 4]
3 3
3
[]
1 6
6
[6]
1 3
3
[6, 3]
1 1
1
[]
1 3
3
[3]
1 3
5
5
[3, 5]
1 6
6
[3, 5, 6]
1 6
3
4
4
[3, 5, 6, 4]
1 4
3
6
6
3
3
5
4
4
6
3
2
2
[3, 5, 6, 4, 2]
1 5
1
1
[]
3 2
2
[2]
3 6
6
[2, 6]
3 2
2
3
3
[]
6 1
1
[1]
6 2
2
[1, 2]
6 1
1
5
5
[1, 2, 5]
6 3
3
[1, 2, 5, 3]
6 2
6
6
[]
5 5
5
[]
5 4
4
[4]
5 6
6
[4, 6]
5 5
5
[]
1 1
1
[]
2 3
3
[3]
2 3
5
5
[3, 5]
2 5
6
6
[3, 5, 6]
2 6
1
1
[3, 5, 6, 1]
2 4
4
[3, 5, 6, 1, 4]
2 2
2
[]
5 6
6
[6]
5 2
2
[6, 2]
5 6
2
4
4
[6, 2, 4]
5 1
1
[6, 2, 4, 1]
5 5
5
[]
5 2
2
[2]
5 3
3
[2, 3]
5 6
6
[2, 3, 6]
5 2
4
4
[2, 3, 6, 4]
5 5
5
[]
6 3
3
[3]
6 6
6
[]
5 3
3
[3]
5 1
1
[3, 1]
5 6
6
[3, 1, 6]
5 3
6
4
4
[3, 1, 6, 4]
5 6
2
2
[3, 1, 6, 4, 2]
5 1
4
4
1
2
6
4
2
2
4
6
3
3
3
1
3
1
1
2
6
1
6
6
3
6
4
6
4
3
3
2
5
5
[]
2 3
3
[3]
2 1
1
[3, 1]
2 1
4
4
[3, 1, 4]
2 6
6
[3, 1, 4, 6]
2 4
1
2
2
[]
5 1
1
[1]
5 1
2
2
[1, 2]
5 1
5
5
[]
5 2
2
[2]
5 2
3
3
[2, 3]
5 4
4
[2, 3, 4]
5 4
3
2
4
2
1
1
[2, 3, 4, 1]
5 5
5
[]
2 3
3
[3]
2 5
5
[3, 5]
2 5
3
2
2
[]
1 5
5
[5]
김결정 has connected to Discord!
김결정 has connected to Discord!
김결정 has connected to Discord!
김결정 has connected to Discord!
김결정 has connected to Discord!
김결정 has connected to Discord!
김결정 has connected to Discord!
김결정 has connected to Discord!
김결정 has connected to Discord!
김결정 has connected to Discord!
김결정 has connected to Discord!
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/http.py", line 258, in static_login
    data = await self.request(Route('GET', '/users/@me'))
  File "/usr/local/lib/python3.6/dist-packages/discord/http.py", line 222, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 401 UNAUTHORIZED (error code: 0): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./decision_kim.py", line 238, in <module>
    client.run(token)
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 598, in run
    return future.result()
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 579, in runner
    await self.start(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 542, in start
    await self.login(*args, bot=bot)
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 400, in login
    await self.http.static_login(token, bot=bot)
  File "/usr/local/lib/python3.6/dist-packages/discord/http.py", line 262, in static_login
    raise LoginFailure('Improper token has been passed.') from exc
discord.errors.LoginFailure: Improper token has been passed.
